package com.msb.api.code;

/**
 * 系统管理模块的错误吗
 * 区间：10000 - 15555
 */
public interface SystemCode {
    // 系统通用的成功状态吗
    String TRAFFIC_SYSTEM_SUCCESS = "000000";
    String TRAFFIC_SYSTEM_ERROR = "000001";
    // 用户管理 10000 - 10999
    /**
     * 错误
     */
    // 10000 - 10499 错误的提示
    String SYSTEM_USER_ERROR_ADD_FAIL = "10000";
    String SYSTEM_USER_ERROR_ADD_FAIL_PARAM_NULL = "10001";
    String SYSTEM_USER_ERROR_ADD_FAIL_NAME_NULL = "10002";
    String SYSTEM_USER_ERROR_ADD_FAIL_NAME_NULL_MSG = "用户名为空"; //仅仅只做演示
    String SYSTEM_USER_ERROR_ADD_FAIL_ACCOUNT_NULL = "10003";
    String SYSTEM_USER_ERROR_ADD_FAIL_PASS_NULL = "10004";
    String SYSTEM_USER_ERROR_ADD_FAIL_PHONE_NULL = "10005";
    String SYSTEM_USER_ERROR_ADD_FAIL_NAME_SIZE = "10006";
    String SYSTEM_USER_ERROR_ADD_FAIL_ACCOUNT_SIZE = "10007";
    String SYSTEM_USER_ERROR_ADD_FAIL_PASS_SIZE = "10008";

    String SYSTEM_USER_ERROR_DELETE_USER_FAIL = "10030";
    String SYSTEM_USER_ERROR_DELETE_USER_FAIL_MSG = "删除用户失败";
    String SYSTEM_USER_ERROR_DELETE_USER_FAIL_PARAM_NULL = "10031";
    String SYSTEM_USER_ERROR_DELETE_USER_FAIL_PARAM_NULL_MSG = "用户ID不能为空";

    String SYSTEM_USER_ERROR_UPD_FAIL_USER_ID_NULL = "10050";
    String SYSTEM_USER_ERROR_UPD_FAIL_USER_ID_NULL_MSG = "用户ID不能为空";
    String SYSTEM_USER_ERROR_UPD_USER_FAIL = "10051";
    String SYSTEM_USER_ERROR_UPD_USER_FAIL_MSG = "用户更新成功";

    /**
     * 提示
     */
    // 10500 -10999 成功的提示
    String SYSTEM_USER_INFO_ADD = "10500";

    // 角色管理 11000 - 11999
    int SYSTEM_ROLE_ERROR_ADD_FAIL = 11000;

    // 权限管理 12000 - 12999
}
